Repository improbable-eng/etcd-cluster-operator, pull requests merged in 2019-11, with the labels that each got.

#58 Communicate with the etcd cluster from inside the controller
  api/v1alpha1/etcdcluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/etcd.improbable.io_etcdclusters.yaml
  controllers/etcdcluster_controller.go
  controllers/suite_test.go
  internal/reconcilerevent/cluster.go
  internal/reconcilerevent/doc.go
  internal/reconcilerevent/event.go
  internal/test/e2e/e2e_test.go
  main.go
Labels: enhancement

#70 Create release notes template
  docs/release-notes/template.md
Labels: documentation

#74 Break the e2e tests into sub-tests and run more in parallel
  internal/test/e2e/e2e_test.go
  internal/test/e2e/fixtures/cluster-client-service.yaml
  internal/test/e2e/kubectl.go
Labels: housekeeping

#72 Update validation
  api/v1alpha1/validation.go
  api/v1alpha1/validation_test.go
Labels: enhancement

#71 Release v0.1.0
  README.md
  docs/contributing.md
  docs/release-notes/v0.1.md
Labels: documentation

#75 Scale up clusters
  api/v1alpha1/etcdcluster_types.go
  api/v1alpha1/etcdpeer_types.go
  config/crd/bases/etcd.improbable.io_etcdclusters.yaml
  config/crd/bases/etcd.improbable.io_etcdpeers.yaml
  config/rbac/role.yaml
  controllers/etcdcluster_controller.go
  controllers/etcdcluster_controller_test.go
  controllers/etcdpeer_controller.go
  controllers/suite_test.go
  internal/etcd/etcd.go
  internal/etcdenvvar/envvars.go
  internal/reconcilerevent/cluster.go
  internal/test/e2e/e2e_test.go
  internal/test/e2e/kubectl.go
  internal/test/examples.go
  main.go
Labels: enhancement

#86 Fixups for cluster scale-up
  internal/test/e2e/e2e_test.go
Labels: housekeeping

#73 Run Circle CI jobs in parallel
  .circleci/config.yml
Labels: housekeeping

#81 Documentation for deleting a cluster and restoring a deleted cluster
  docs/operations.md
Labels: documentation

#78 Make it easier to re-use an existing Kind cluster for E2E tests
  Makefile
  docs/contributing.md
  internal/test/e2e/e2e_test.go
Labels: housekeeping

#88 EventuallyInCluster: a helper to run a command in the cluster and wai…
  internal/test/e2e/e2e_test.go
  internal/test/e2e/kubectl.go
Labels: bug

#94 Debug docker build
  Dockerfile
  Makefile
  internal/test/e2e/e2e_test.go
Labels: enhancement

#93 Scale down
  .circleci/config.yml
  Makefile
  api/v1alpha1/validation.go
  api/v1alpha1/validation_test.go
  config/rbac/role.yaml
  controllers/etcdcluster_controller.go
  controllers/etcdcluster_controller_test.go
  controllers/suite_test.go
  docs/operations.md
  internal/reconcilerevent/cluster.go
  internal/test/e2e/e2e_test.go
  internal/test/e2e/kubectl.go
  internal/test/e2e/testdata/zero-resource-quota.yaml
  internal/test/log.go
Labels: enhancement

#65 Implement backup resource controller
  api/v1alpha1/etcdbackup_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/etcd.improbable.io_etcdbackups.yaml
  config/rbac/role.yaml
  config/test/e2e/backup/etcdbackup.yaml
  config/test/e2e/backup/etcdcluster.yaml
  controllers/etcdbackup_controller.go
  go.mod
  go.sum
  internal/backup/destination.go
  internal/backup/doc.go
  internal/backup/method.go
  internal/test/e2e/e2e_test.go
  internal/test/e2e/kubectl.go
  main.go
Labels: enhancement
